Improve slider style for desktop and add horizontal separator
kryptokrauts/kk-website pull request #60
Opened 2019-08-15 18:58 UTC by the-icarus

2019-08-15 20:55 UTC, marc0olo commented
@the-icarus would it be possible to have the desktop view of A-Z sticky?

2019-08-15 21:21 UTC, marc0olo requested changes
@the-icarus would it be possible to have the desktop view of A-Z sticky?

2019-08-28 15:42 UTC, the-icarus commented
@marc0olo Slider is now sticky. Did a rebase so you might need to do a fresh checkout

2019-08-29 05:35 UTC, marc0olo approved these changes

2019-08-29 05:35 UTC, merged